name: CI/CD Pipeline Example with Pytest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4.2.2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run all tests (Frontend and Backend)
        run: |
          echo "Running all tests..."
          pytest tests/frontend/test_login.py tests/backend/test_checkout.py --junitxml=report.xml --maxfail=1 --disable-warnings --capture=no || true

      - name: Upload test report
        uses: actions/upload-artifact@v4.6.2
        with:
          name: test-report
          path: report.xml

      - name: Generate test summary
        run: |
          # Parse the report.xml file for test results
          PASS_COUNT=$(grep -o 'tests/.*PASSED' report.xml | wc -l || echo 0)
          FAIL_COUNT=$(grep -o 'tests/.*FAILED' report.xml | wc -l || echo 0)
          echo "Test Result: Passed $PASS_COUNT, Failed $FAIL_COUNT"
          echo "Test Summary: {\"passed\": $PASS_COUNT, \"failed\": $FAIL_COUNT}" > test_summary.json


      - name: Upload test summary
        uses: actions/upload-artifact@v4.6.2
        with:
          name: test-summary
          path: test_summary.json
